repos:
  - repo: local
    hooks:
      - id: make-format
        name: make format
        entry: make format
        language: system
        pass_filenames: false
        always_run: true
        stages: [pre-commit]
      - id: make-test
        name: make test
        entry: make test
        language: system
        pass_filenames: false
        always_run: true
        stages: [pre-commit]
      - id: make-lit-coverage-check
        name: make lit-coverage-check
        entry: make lit-coverage-check
        language: system
        pass_filenames: false
        always_run: true
        stages: [pre-commit]
