FROM --platform=linux/amd64 ghcr.io/astral-sh/uv:python3.11-bookworm-slim

RUN uv pip install --system --no-cache --prerelease=allow \
    --extra-index-url https://download.pytorch.org/whl/nightly/cpu \
    --find-links https://github.com/llvm/torch-mlir-release/releases/expanded_assets/dev-wheels \
    torch-mlir torchvision onnx

WORKDIR /workspace
